/*
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import it.unibz.inf.ontouml.xtext.ide.contentassist.antlr.internal.InternalOntoUMLParser;
import it.unibz.inf.ontouml.xtext.services.OntoUMLGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class OntoUMLParser extends AbstractContentAssistParser {

	@Inject
	private OntoUMLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalOntoUMLParser createParser() {
		InternalOntoUMLParser result = new InternalOntoUMLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelElementAccess().getAlternatives(), "rule__ModelElement__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_3(), "rule__Model__Group_3__0");
					put(grammarAccess.getModelAccess().getGroup_3_3(), "rule__Model__Group_3_3__0");
					put(grammarAccess.getModelElement_ImplAccess().getGroup(), "rule__ModelElement_Impl__Group__0");
					put(grammarAccess.getOntoUMLClassAccess().getGroup(), "rule__OntoUMLClass__Group__0");
					put(grammarAccess.getModelAccess().getElementsAssignment_3_2(), "rule__Model__ElementsAssignment_3_2");
					put(grammarAccess.getModelAccess().getElementsAssignment_3_3_1(), "rule__Model__ElementsAssignment_3_3_1");
					put(grammarAccess.getOntoUMLClassAccess().getNameAssignment_2(), "rule__OntoUMLClass__NameAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public OntoUMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OntoUMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
