/*
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.serializer;

import com.google.inject.Inject;
import it.unibz.inf.ontouml.xtext.services.OntoUMLGrammarAccess;
import it.unibz.inf.ontouml.xtext.xcore.Model;
import it.unibz.inf.ontouml.xtext.xcore.ModelElement;
import it.unibz.inf.ontouml.xtext.xcore.OntoUMLClass;
import it.unibz.inf.ontouml.xtext.xcore.XcorePackage;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class OntoUMLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private OntoUMLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == XcorePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case XcorePackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case XcorePackage.MODEL_ELEMENT:
				sequence_ModelElement_Impl(context, (ModelElement) semanticObject); 
				return; 
			case XcorePackage.ONTO_UML_CLASS:
				sequence_OntoUMLClass(context, (OntoUMLClass) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     ModelElement returns ModelElement
	 *     ModelElement_Impl returns ModelElement
	 *
	 * Constraint:
	 *     {ModelElement}
	 */
	protected void sequence_ModelElement_Impl(ISerializationContext context, ModelElement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (elements+=ModelElement elements+=ModelElement*)?
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ModelElement returns OntoUMLClass
	 *     OntoUMLClass returns OntoUMLClass
	 *
	 * Constraint:
	 *     name=EString
	 */
	protected void sequence_OntoUMLClass(ISerializationContext context, OntoUMLClass semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XcorePackage.Literals.ONTO_UML_CLASS__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XcorePackage.Literals.ONTO_UML_CLASS__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOntoUMLClassAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
